name: Build TWRP for OnePlus Nord CE 3 Lite 5G

on:
  push:
    branches:
      - main

jobs:
  build_twrp:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        sudo apt update
        sudo apt install -y repo git curl bc bison flex g++-multilib jq libssl-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop python3 python3-pip python3-venv rsync scons sudo zip zlib1g-dev

    - name: Clone LineageOS Device Tree for OnePlus Nord CE 3 Lite 5G
      run: |
        git clone https://github.com/LineageOS/android_device_oneplus_larry.git device/oneplus/larry

    - name: Modify Device Tree for TWRP
      run: |
        # Navigate to the device tree directory
        cd device/oneplus/larry

        # Remove boot-specific files
        rm -rf init.rc init.larry.rc

        # Create or modify recovery.fstab for TWRP
        cat <<EOL > recovery.fstab
/dev/block/bootdevice/by-name/system   /system      ext4    ro
/dev/block/bootdevice/by-name/vendor   /vendor      ext4    ro
/dev/block/bootdevice/by-name/cache    /cache       ext4    rw
/dev/block/bootdevice/by-name/recovery /recovery    emmc    rw
EOL

        # Modify Android.mk or Boardconfig.mk for TWRP kernel configuration
        # (This is just a sample, you'll need to modify it based on your kernel config)
        echo "BOARD_KERNEL_CMDLINE := androidboot.selinux=permissive" >> Boardconfig.mk
        
    - name: Clone TWRP AOSP Manifest
      run: |
        git clone https://github.com/TeamWin/android_bootable_recovery -b twrp-12.1 platform/bootable/recovery

    - name: Setup TWRP Build Environment
      run: |
        # Initialize the TWRP build environment
        cd platform/bootable/recovery
        repo init -u https://github.com/TeamWin/android_bootable_recovery -b twrp-12.1
        repo sync

    - name: Set up kernel for recovery
      run: |
        # Clone the kernel (use the correct kernel source repo for the OnePlus Nord CE 3 Lite 5G)
        git clone https://github.com/LineageOS/android_kernel_oneplus_larry.git kernel/oneplus/larry

    - name: Build TWRP
      run: |
        # Initialize the build environment and set up for the OnePlus device
        . build/envsetup.sh
        lunch twrp_larry-userdebug
        mka recoveryimage

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: twrp-recovery-image
        path: out/target/product/larry/recovery.img
