name: Build TWRP Recovery

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf \
            imagemagick lib32ncurses5-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev \
            libxml2 libxml2-utils lzop openjdk-11-jdk python3 python3-pip unzip xz-utils zip zlib1g-dev \
            repo

      - name: Set up repo and sync sources
        run: |
          mkdir -p ~/twrp && cd ~/twrp
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
          repo sync -j$(nproc) --force-sync

      - name: Clone device tree
        run: |
          mkdir -p ~/twrp/device/oneplus/larry
          git clone https://github.com/LineageOS/android_device_oneplus_larry ~/twrp/device/oneplus/larry

      - name: Set up build environment
        run: |
          cd ~/twrp
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_larry-eng

      - name: Build TWRP
        run: |
          cd ~/twrp
          mka bootimage vendor_bootimage dtboimage recoveryimage

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twrp-images
          path: |
            ~/twrp/out/target/product/larry/boot.img
            ~/twrp/out/target/product/larry/vendor_boot.img
            ~/twrp/out/target/product/larry/dtbo.img
            ~/twrp/out/target/product/larry/recovery.img

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ~/twrp/out/target/product/larry/boot.img
            ~/twrp/out/target/product/larry/vendor_boot.img
            ~/twrp/out/target/product/larry/dtbo.img
            ~/twrp/out/target/product/larry/recovery.img
          tag_name: latest
          name: TWRP Build for OnePlus Larry
          body: |
            Latest TWRP build for OnePlus Larry
            
            - Boot Image
            - Vendor Boot Image
            - DTBO Image
            - Recovery Image
          draft: false
          prerelease: false
